// Code generated by hero.
// source: C:\E\project\golang\src\github_s\go_movies\views\hero\m3u8.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func M3u8(show map[string]interface{}, buffer *bytes.Buffer) {
	buffer.WriteString(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>play</title>
    <meta name="referrer" content="never">
    <script type="text/javascript" src="/static/org/ckplayer/ckplayer/ckplayer.js"></script>
</head>
<body>

<div id="video" style="width:100%;height:100%;"></div>
<script type="text/javascript">
    var videoObject = {
        container: '#video',//“#”代表容器的ID，“.”或“”代表容器的class
        variable: 'player',//该属性必需设置，值等于下面的new chplayer()的对象
        flashplayer:false,//如果强制使用flashplayer则设置成true
        video:"`)
	hero.EscapeHTML(show["play_url"].(string), buffer)
	buffer.WriteString(`" //视频地址
    };
    var player=new ckplayer(videoObject);
</script>

</body>
</html>
`)

}
